var express=require('express')
var app=express()
var login=require('./login.js')
var signup=require('./signup.js')
var home=require('./home.js')
var upload=require('./filePost.js')
var check=require('./check.js')
var visual=require('./visual.js')
var fetch=require('./fetch.js')
app.use(login)
app.use(signup)
app.use(home)
app.use(upload)
app.use(check)
app.use(visual)
app.use(fetch)
app.listen(process.env.PORT, '0.0.0.0')